### ISSUE TITLE
Development version bug: webform_components "Type" is too short

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/stripe_checkout#8]
This is an issue in the development version I am working on which incorporates some webform functionality (not the current live release) but I'm adding it here to keep note of it.

Short form -- a webform is trying to save "stripe_checkout_webform" as a value in the Type field in `webform_components` but the field is too short. Simplest solution would be to enlarge that field (currently only 16 characters allowed) but would need to talk to webform maintainers to see if that is agreeable. When I update that manually to VARCHAR / 32 it does not give this error and inserts correctly.

`PDOException: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'type' at row 1: INSERT INTO {webform_component} (nid, cid, pid, form_key, name, type, value, extra, required, weight) VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3, :db_insert_placeholder_4, :db_insert_placeholder_5, :db_insert_placeholder_6, :db_insert_placeholder_7, :db_insert_placeholder_8, :db_insert_placeholder_9); Array ( [:db_insert_placeholder_0] => 2 [:db_insert_placeholder_1] => 2 [:db_insert_placeholder_2] => 0 [:db_insert_placeholder_3] => stripe_checkout [:db_insert_placeholder_4] => Stripe Checkout [:db_insert_placeholder_5] => stripe_checkout_webform [:db_insert_placeholder_6] => [:db_insert_placeholder_7] => a:7:{s:15:"wrapper_classes";s:0:"";s:9:"test_mode";i:1;s:11:"amount_type";s:4:"plan";s:23:"amount_value_multiplier";s:3:"100";s:11:"amount_plan";s:5:"plan1";s:10:"image_file";i:0;s:7:"private";i:0;} [:db_insert_placeholder_8] => 0 [:db_insert_placeholder_9] => 1 ) in webform_component_insert() (line 787 of /Users/laryn/buildkit/build/backdrop-demo/modules/webform/includes/webform.components.inc).`

**Comment by jenlampton** [comment]
I just had a quick chat with @quicksketch and he recommended the component name be simply "stripe". Any reason to include the module name in there?

**Comment by laryn** [comment]
I think that's fine -- especially given that we're renaming `stripe_api` as `stripe` and incorporating this into that.

**Comment by laryn** [comment]
Closing this issue as this module is no longer maintained. Stripe development is now centering around
the [Stripe](https://github.com/backdrop-contrib/stripe) module, including the bundled `webform_stripe` functionality.
